#!/usr/bin/env bash
# decisions-index.sh: regenerate the Decisions index from the D-*.md files.
#
# Decisions are named D-YYYYMMDD-<author>-<slug>.md. The filesystem is the SSOT.
# There is no sequential number and no "next id" to coordinate: a new decision
# uses today's date, the author handle, and a slug, so two people on parallel
# branches never collide. This script reads every decision file, pulls
# date/author/title/status, and rewrites one generated region in
# docs/wiki/decisions/README.md:
#   <!-- index:table --> ... <!-- /index:table -->
# Do not hand-edit that region; merge conflicts resolve by re-running the script.
#
# Usage:
#   bash scripts/decisions-index.sh           # rewrite README in place
#   bash scripts/decisions-index.sh --check    # exit 1 if README is stale (CI)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

README="docs/wiki/decisions/README.md"
DECISIONS_DIR="docs/wiki/decisions"

if [ ! -f "$README" ]; then
  echo "[decisions-index] $README not found" >&2
  exit 1
fi

MODE="${1:-write}"

python3 - "$README" "$DECISIONS_DIR" "$MODE" <<'PY'
import sys, re, glob, os

readme_path, decisions_dir, mode = sys.argv[1], sys.argv[2], sys.argv[3]

# Collect decision files: D-YYYYMMDD-<author>-<slug>.md, excluding the template.
entries = []
for path in sorted(glob.glob(os.path.join(decisions_dir, "D-*.md"))):
    name = os.path.basename(path)
    if name == "D-template.md" or name.endswith(".template.md"):
        continue
    did = name[:-3]  # strip .md
    m = re.match(r"D-(\d{8})-", name)
    date_key = m.group(1) if m else "00000000"
    text = open(path, encoding="utf-8").read()
    sm = re.search(r"^status:\s*(\S+)", text, re.M)
    status = sm.group(1).strip() if sm else "draft"
    tm = re.search(r"^#\s+(.+)$", text, re.M)
    title = tm.group(1).strip() if tm else did
    title = re.sub(r"^D-\S+\s*[:\-]\s*", "", title).strip()
    entries.append((date_key, did, title, status))

# chronological (oldest first), then by id
entries.sort(key=lambda e: (e[0], e[1]))

if entries:
    rows = ["| ID | Title | Status |", "|---|---|---|"]
    for _, did, title, status in entries:
        rows.append("| `%s` | %s | %s |" % (did, title, status))
    table = "\n".join(rows)
else:
    table = ("| ID | Title | Status |\n"
             "|---|---|---|\n"
             "| _none yet_ | Copy `D-template.md` to `D-YYYYMMDD-<author>-<slug>.md`, then run `scripts/decisions-index.sh` | |")

orig = open(readme_path, encoding="utf-8").read()

start = "<!-- index:table (generated by scripts/decisions-index.sh) -->"
end = "<!-- /index:table -->"
pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
if not pat.search(orig):
    raise SystemExit("[decisions-index] marker %s not found in README" % start)
new = pat.sub(lambda _: start + "\n" + table + "\n" + end, orig, count=1)

if mode == "--check":
    if new != orig:
        print("[decisions-index] STALE: run `bash scripts/decisions-index.sh`", file=sys.stderr)
        sys.exit(1)
    print("[decisions-index] index up to date (%d decisions)" % len(entries))
else:
    if new != orig:
        open(readme_path, "w", encoding="utf-8").write(new)
        print("[decisions-index] regenerated (%d decisions)" % len(entries))
    else:
        print("[decisions-index] no change (%d decisions)" % len(entries))
PY
